branches:
  only:
  - master
  - stable
language: java
jdk:
- openjdk14
dist: focal
before_install:
install:
- "./ci/before-deploy.sh"
before_script: 
script: 
after_success:
- "echo $BINTRAY_USER;./ci/deploy.sh"
after_failure:
